[package]
name = "lib-simulation"
version = "0.1.0"
authors = ["0xlmnt <contact@lmntl.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = {version = "0.27.1", features = ["rand-no-std"]}
rand = "0.8.4"
